In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
x1 = torch.tensor([[7],[0],[7]],dtype=torch.float32).view(1,3)
x2 = torch.tensor([[0],[7],[0]],dtype=torch.float32).view(1,3)
y1 = torch.tensor([[7]],dtype=torch.float32)
y2 = torch.tensor([[0]],dtype=torch.float32)


w1 = torch.tensor([[0.7,0],[2.1,0],[3.5,0]],dtype=torch.float32)
w1 = torch.transpose(w1,1,0)
w2 = torch.tensor([[7.15,7.25,7.35],[0.45,0.55,0.65]],dtype=torch.float32)
w2 = torch.transpose(w2,1,0)
w3 = torch.tensor([[0.12,0.22],[0.32,0.42],[0.52,0.62]],dtype=torch.float32)
w3 = torch.transpose(w3,1,0)
w4 = torch.tensor([[7.16,7.36]],dtype=torch.float32)

b1 = torch.tensor([[0.7],[0]],dtype=torch.float32)
b1 = torch.transpose(b1,1,0)
b2 = torch.tensor([[7.15],[7.25],[7.35]],dtype=torch.float32)
b2 = torch.transpose(b2,1,0)
b3 = torch.tensor([[7.12],[7.22]],dtype=torch.float32)
b3 = torch.transpose(b3,1,0)
b4 = torch.tensor([6.74],dtype=torch.float32)

In [3]:
class MyNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(3,2)
    self.fc1.weight = nn.Parameter(w1)
    self.fc1.bias = nn.Parameter(b1)

    self.tanh= nn.Tanh()
    
    self.fc2 = nn.Linear(2,3)
    self.fc2.weight = nn.Parameter(w2)
    self.fc2.bias = nn.Parameter(b2)

    self.sigmoid= nn.Sigmoid()

    self.fc3 = nn.Linear(3,2)
    self.fc3.weight = nn.Parameter(w3)
    self.fc3.bias = nn.Parameter(b3)

    self.fc4 = nn.Linear(2,1)
    self.fc4.weight = nn.Parameter(w4)
    self.fc4.bias = nn.Parameter(b4)

    self.relu1= nn.ReLU()

  def forward(self, input):
    y = self.fc1(input)
    y = self.tanh(y)
    y = self.fc2(y)
    y = self.sigmoid(y)
    y = self.fc3(y)
    y = self.tanh(y)
    y = self.fc4(y)
    y = self.relu1(y)
    return y


mymodel = MyNN()
criterion = nn.MSELoss()
opt = torch.optim.SGD(mymodel.parameters(),lr = 0.1)

### First Update

In [4]:
output = mymodel.forward(x1)
loss = criterion(y1, output)/2
loss.backward()
opt.step()
opt.zero_grad()

In [5]:
w11 = np.transpose(mymodel.fc1.weight.detach().numpy().round(3))
w12 = np.transpose(mymodel.fc2.weight.detach().numpy().round(3))
w13 = np.transpose(mymodel.fc3.weight.detach().numpy().round(3))
w14 = np.transpose(mymodel.fc4.weight.detach().numpy().round(3))

b11 = np.transpose(mymodel.fc1.bias.detach().numpy().round(3))
b12 = np.transpose(mymodel.fc2.bias.detach().numpy().round(3))
b13 = np.transpose(mymodel.fc3.bias.detach().numpy().round(3))
b14 = np.transpose(mymodel.fc4.bias.detach().numpy().round(3))
print("Weights biases after first update:")
print("W1:")
print(w11)
print("B1:")
print(b11)
print("W2:")
print(w12)
print("B2:")
print(b12)
print("W3:")
print(w13)
print("B3:")
print(b13)
print("W4:")
print(w14)
print("B4:")
print(b14)

Weights biases after first update:
W1:
[[ 0.7 -0. ]
 [ 2.1  0. ]
 [ 3.5 -0. ]]
B1:
[[ 0.7]
 [-0. ]]
W2:
[[7.15 7.25 7.35]
 [0.45 0.55 0.65]]
B2:
[[7.15]
 [7.25]
 [7.35]]
W3:
[[0.12 0.22]
 [0.32 0.42]
 [0.52 0.62]]
B3:
[[7.12]
 [7.22]]
W4:
[[5.734]
 [5.934]]
B4:
[5.314]


### Second Update

In [6]:
output = mymodel.forward(x2)
loss = criterion(y2, output)/2
loss.backward()
opt.step()
opt.zero_grad()

In [7]:
w21 = np.transpose(mymodel.fc1.weight.detach().numpy().round(3))
w22 = np.transpose(mymodel.fc2.weight.detach().numpy().round(3))
w23 = np.transpose(mymodel.fc3.weight.detach().numpy().round(3))
w24 = np.transpose(mymodel.fc4.weight.detach().numpy().round(3))

b21 = np.transpose(mymodel.fc1.bias.detach().numpy().round(3))
b22 = np.transpose(mymodel.fc2.bias.detach().numpy().round(3))
b23 = np.transpose(mymodel.fc3.bias.detach().numpy().round(3))
b24 = np.transpose(mymodel.fc4.bias.detach().numpy().round(3))
print("Weights biases after second update:")
print("W1:")
print(w21)
print("B1:")
print(b21)
print("W2:")
print(w22)
print("B2:")
print(b22)
print("W3:")
print(w23)
print("B3:")
print(b23)
print("W4:")
print(w24)
print("B4:")
print(b24)

Weights biases after second update:
W1:
[[ 0.7 -0. ]
 [ 2.1 -0. ]
 [ 3.5 -0. ]]
B1:
[[ 0.7]
 [-0. ]]
W2:
[[7.15 7.25 7.35]
 [0.45 0.55 0.65]]
B2:
[[7.15]
 [7.25]
 [7.35]]
W3:
[[0.12 0.22]
 [0.32 0.42]
 [0.52 0.62]]
B3:
[[7.12]
 [7.22]]
W4:
[[4.036]
 [4.236]]
B4:
[3.616]
